### ISSUE TITLE
Add ORCIDs to DESCRIPTION

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/rotl#107]
@josephwb @dwinter what are your ORCID? They can be added as a comment in DESCRIPTION now, so it could be nice to include them.

> Hyperlinks in package DESCRIPTION files on CRAN
For  package  authors  specified  via  an  ‘
Authors@R
’  field  in  the  DESCRIPTION  file,
ORCID  identifiers  (see
https://orcid.org/
for  more  information)  can  be  provided
via  elements  named  ‘
ORCID
’  in  the
comment
argument  of  the
person()
calls,   e.g.,
person("Achim","Zeileis",comment = c(ORCID = "0000-0003-0918-3766"))
. These iden-
tifiers will then be hyperlinked in the CRAN pa

**Comment by josephwb** [comment]
https://orcid.org/0000-0002-3835-8062

**Comment by fmichonneau** [comment]
Thanks. @dwinter I think I have the right one for you. Let me know if not.

**Comment by dwinter** [comment]
Thanks @fmichonneau. Living in another timezone is great, you can open and close an issue while I sleep with no work required me at all!  :sleeping_bed:
