### ISSUE TITLE
Mus isn't a mouse?

### ISSUE THREAD

**Issue by bomeara** [ropensci/rotl#113]
`tnrs_match_names("Mus")` returns

 ```
  search_string                unique_name approximate_match  ott_id is_synonym  flags number_matches
1           mus Mus (genus in Protostomia)             FALSE 5693416      FALSE BARREN              3
```

In OT, there are two *Mus*:

https://tree.opentreeoflife.org/opentree/argus/ottol@5693416/Mus-genus-in-Protostomia- , where it says "This taxon is in our taxonomy but not in our tree synthesis database. This can happen for a variety of reasons, but the most probable is that is has a taxon flag (e.g. incertae sedis) that causes it to be pruned from the synthetic tree. See the taxonomy browser for more information about this taxon."

and 
https://tree.opentreeoflife.org/opentree/argus/ottol@1068778/Mus-genus-in-Deuterostomia-, which is our beloved 🐭 . rotl is only returning the first one. It would probably work if we give it a context, but for our use case, we generally won't know the context.

**Comment by fmichonneau** [comment]
This is how rotl can deal with these situations:

```r
> mus <- tnrs_match_names("mus")
> mus
  search_string                unique_name approximate_match  ott_id is_synonym
1           mus Mus (genus in Protostomia)             FALSE 5693416      FALSE
   flags number_matches
1 BARREN              3
> inspect(mus, row_number = 1)
  search_string                  unique_name approximate_match  ott_id
1           mus   Mus (genus in Protostomia)             FALSE 5693416
2           mus Mus (genus in Deuterostomia)             FALSE 1068778
3           mus                 Mus musculus             FALSE  542509
  is_synonym          flags number_matches
1      FALSE         BARREN              3
2      FALSE SIBLING_HIGHER              3
3       TRUE                             3
> mus <- update(mus, row_number = 1, new_ott_id = 1068778)
> mus
  search_string                  unique_name approximate_match  ott_id
1           mus Mus (genus in Deuterostomia)             FALSE 1068778
  is_synonym          flags number_matches
1      FALSE SIBLING_HIGHER              3
```

I haven't looked at it in a while, but I don't think there are other ways than doing it manually. I'd be interested to hear if you have better ideas for a better approach.

**Comment by bomeara** [comment]
Thanks. Do you advise doing a barren hack PR for rotl or wait for the OT fix?

**Comment by mtholder** [comment]
It's probably faster to do the barren hack. There may be other flags that should trigger suppression, too, though. So that might not cover all cases.

**Comment by TonyRees** [comment]
Actually WoRMS does contain the mammal, so the 2 names appear as duplicates though in reality they are the same.
