### ISSUE TITLE
Error in rncl(file = file, ...)

### ISSUE THREAD

**Issue by TarekHattab** [ropensci/rotl#114]
Hi,

I tried to apply the function « tol_induced_subtree » as shown in the "README.md" example. 

apes <- c("Pongo", "Pan", "Gorilla", "Hoolock", "Homo")
(resolved_names <- tnrs_match_names(apes))
tr <- tol_induced_subtree(ott_ids=ott_id(resolved_names))

I got the following message

Error in rncl(file = file, ...) : 
  Expecting a tree description, but found "{" instead

I get the same message on Linux and Windows OS. I have used this function several times before the update of the package without any problem. Do you have an idea about this bug?

**Comment by fmichonneau** [comment]
Thanks for bringing this up to our attention.

It seems to come from changes to the OpenTree of Life API. I reported this https://github.com/OpenTreeOfLife/feedback/issues/421

**Comment by fmichonneau** [comment]
The OpenTreeofLife fixed things upstream, and it seems to be working now. Please re-open if it's not the case.
