### ISSUE TITLE
tnrs_match_names and  tol_induced_subtree only pull 250 species

### ISSUE THREAD

**Issue by akahrl** [ropensci/rotl#117]
I'm trying to make a tree with ~4000 species, but when I try to load more than 250 species from my taxa list using 'tnrs_match_names' I get the following error:

> taxa <- tnrs_match_names(unique(sperm[1:251, 1]), context="Animals")

Error: HTTP failure: 400
Queries containing more than 250 strings are not supported. You may submit multiple smaller queries to avoid this limit.BadInputExceptionorg.neo4j.server.rest.repr.BadInputExceptionlist("org.opentree.taxonomy.plugins.tnrs_v3.match_names(tnrs_v3.java:241)", "java.lang.reflect.Method.invoke(Method.java:498)", "org.neo4j.server.plugins.PluginMethod.invoke(PluginMethod.java:57)","org.neo4j.server.plugins.PluginManager.invoke(PluginManager.java:168)","org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:300)","org.neo4j.server.rest.web.ExtensionService.invokeGraphDatabaseExtension(ExtensionService.java:122)","java.lang.reflect.Method.invoke(Method.java:498)", "org.neo4j.server.rest.security.SecurityFilter.doFilter(SecurityFilter.java:112)")

Any idea what is going wrong? The function works perfectly when I have 250 species or less.

The error suggested that I could submit multiple smaller queries, which I did, then concatenated the results. When I tried using this complete list and running 'tol_induced_subtree' it again only returns a tree with the first 250 species. I don't get an error message when this happens, only the normal warning: Warning in collapse_singles(tr, show_progress): Dropping singleton nodes
## with labels...

Any ideas here?

**Comment by josephwb** [comment]
OT does have a limit on the number of tips, but this is 25K or 100K (depending on the format). I just successfully got an induced tree of 357 hummingbirds. So maybe something went wrong when you concatenated the ids?

**Comment by akahrl** [comment]
Huh, the function 'tol_induced_subtree' seems to be working now (though I need to move through ott ids that aren't found).

Any idea why the function 'tnrs_match_names' doesn't work? I don't mind taking some extra steps to make a larger dataframe, but it would be nice to have the function run in one go.

Thanks for the help!

**Comment by josephwb** [comment]
Yeah, that is a hard limit for the TNRS fuzzy matching. I'm afraid I am not aware of how to get around it (i.e., by turning off the fuzzy match).

**Comment by kavyaaswadhati** [comment]
@akahrl Did you change anything in your script to get the 'top_induced_subtree' function to work? I am running up against the same error where I call the 'tnrs_match_names' function in batches and the resultant data frame is the appropriate length, but the induced tree built off of it still only contains the first 250 species.

**Comment by EcoRSyst** [comment]
Hi, i have the same problem where i try to get a tree for more than 250 species. 
I've tried to run the "tnrs_match_names" function on the sliced data two times but when i try to get the tree, i get the error message following : 
`Error in .tol_induced_subtree(ott_ids = ott_ids, node_ids = node_ids,  : 
  At least two valid ‘ott_ids’ or ‘node_ids’ must be ``provided.`

Is it the way i concatened the data frames that cause this error ? 

Thanks for your help

`data_1 <-slice(data, 1:250)`
`data_2 <-slice(data, 251:397)`

`taxon_search_1 <- tnrs_match_names(unique(data_1$Genera), context="Animals")`
`taxon_search_2 <- tnrs_match_names(unique(data_2$Genera), context="Animals")`

`knitr::kable(taxon_search_1)`
`knitr::kable(taxon_search_2)`

`taxon_search <- bind_rows(taxon_search_1,taxon_search_2)`
`knitr::kable(taxon_search)`

`taxon_map <- structure(taxon_search$search_string, names = taxon_search$unique_name)`

`tr <- tol_induced_subtree(ott_id(taxon_search)[is_in_tree(ott_id(taxon_search))])`

**Comment by akahrl** [comment]
So sorry for the super late reply (parental leave). As josephwb pointed out, there is a limit to the TNRS fuzzy matching. I changed my code to this:

taxa <- tnrs_match_names(unique(data[1:4176, 1]), context="Animals", do_approximate_matching=FALSE)

And it solved the problem.
