### ISSUE TITLE
Adding annotation to trees is not possible because of the lack of edge lengths

### ISSUE THREAD

**Issue by lhgergo** [ropensci/rotl#120]
Hi!
I have some taxon-specific data, that I'd like to map on the synthetic tree, that I could get by using the tol_induced_subtree(ott_ids) expression. The ott_ids are the following:

> 201128 252145 779555 694358 542509 271555 770315 490099 730013 338023 857184 623689 755235  50826 850936 619502 301743

Everything had been working fine until I tried to add a given annotation to the tree, using the described method in "Connect your data to the tips of your tree" section of the vignette. When I tried to plot the results using phylo4d I got the following error message:

> Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
>   Viewport has zero dimension(s)
> 

I also got a plot, containing species names and the annotations, but the tree is missing from the plot.
![image](https://user-images.githubusercontent.com/15161219/63014328-92db7480-be8e-11e9-922d-a3daf9ac03de.png)

I've found that in the tree object, produced by tol_induced_subtree() an element edge.length is missing. This was the only difference I found when I compared my dataset to working examples found online. Why is this missing from my object, and how could I solve the problem? Or is it a bug?

Thanks!

**Comment by ArthurPERE** [comment]
Hi, 

I have the same problem than you, there is no branch length, so I can't see all the nearer species among others.

Dis you find a solution or at least download another tree of life with the branch length.

Thank you

**Comment by fmichonneau** [comment]
The trees returned by the Open Tree of Life do not have branch lengths. These trees are only intended to show the relationships and do not include a measure of evolutionary distance. You could add arbitrary branch lengths to the trees so they can be plotted with phylobase. The ape package allows you to plot trees with no branch lengths.

**Comment by fmichonneau** [comment]
this is not an issue with rotl _per se_, closing.

**Comment by bschilder** [comment]
@lhgergo @ArthurPERE 
[TimeTree](http://www.timetree.org/) seems to be a better resource for this, but the associated R package [`timetree`](https://cran.r-project.org/web/packages/timetree/index.html) hasn't been updated since 2015 and appears to not longer work.
