### ISSUE TITLE
Tips not ordered alphabetically for polytomies

### ISSUE THREAD

**Issue by crodriguez-saltos** [ropensci/rotl#125]
When downloading tress using `tol_induced_subtree`, the values of tip.label in the returned object are not ordered alphabetically for polytomies -- even though they are in the plot. Other packages in R expect alphabetical order for polytomies. One of them is `phytools`, for example. When mapping characters onto phylogenies using phytools::plotTree.barplot, unordered tips result in incorrect mappings of characters. In another example, when reading nexus files using ape::read.tree, the tips inside polytomies are ordered alphabetically -- in fact, a work around my issue is to save the tree to a nexus file and then read it back. To use `rotl` alongside other packages, it would help if branch tips follow that convention.

The following code replicates the issue:

```
library(rotl)
sp <- c(
  "Chaetura brachyura",
  "Chaetura cinereiventris",
  "Chaetura pelagica"
)

sp.ott <- tnrs_match_names(sp)$ott_id

tree <- tol_induced_subtree(sp.ott)

# In the following plot, the tips are ordered alphabetically (descending order)
plot(tree)

# But the stored values are not
tree$tip.label
```

The code was run in R v. 3.6.3, rotl v. 3.0.10. The computer was running on Debian GNU/Linux 10 (buster), x86_64-pc-linux-gnu (64-bit).

**Comment by fmichonneau** [comment]
Thanks for reporting this @crodriguez-saltos. I'm relunctant to do anything about this on rotl side because of a `phytools` requirement. It seems to me that it'd be best addressed by `phytools` which should have a function to perform this re-ordering.

**Comment by fmichonneau** [comment]
closing as this is not an rotl issue
