### ISSUE TITLE
tnrs_match_names bug

### ISSUE THREAD

**Issue by sckott** [ropensci/rotl#126]
same problem with CRAN and github versions of `rotl`

noticed this when working on taxize tests, this is a test that used to work, but no errors

```r
tnrs_match_names(names = "Nautilas", do_approximate_matching = FALSE)
#> Error in names(summary_match) <- c(names(tnrs_columns), "number_matches") :
#>   'names' attribute [7] must be the same length as the vector [0]
#> In addition: Warning message:
#> In check_tnrs(res) : Nautilas are not matched
```

<details> <summary><strong>Session Info</strong></summary>

```r
─ Session info ───────────
 setting  value
 version  R version 3.6.3 Patched (2020-03-11 r78210)
 os       macOS Catalina 10.15.4
 system   x86_64, darwin15.6.0
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       US/Pacific
 date     2020-04-17

─ Packages ────────────
 package     * version  date       lib source
 ape           5.3      2019-03-17 [1] CRAN (R 3.6.0)
 assertthat    0.2.1    2019-03-21 [1] CRAN (R 3.6.0)
 backports     1.1.6    2020-04-05 [1] CRAN (R 3.6.2)
 callr         3.4.3    2020-03-28 [1] CRAN (R 3.6.2)
 cli           2.0.2    2020-02-28 [1] CRAN (R 3.6.0)
 crayon        1.3.4    2017-09-16 [1] CRAN (R 3.6.0)
 curl          4.3      2019-12-02 [1] CRAN (R 3.6.0)
 fansi         0.4.1    2020-01-08 [1] CRAN (R 3.6.0)
 glue          1.4.0    2020-04-03 [1] CRAN (R 3.6.2)
 hms           0.5.3    2020-01-08 [1] CRAN (R 3.6.0)
 httr          1.4.1    2019-08-05 [1] CRAN (R 3.6.0)
 jsonlite      1.6.1    2020-02-02 [1] CRAN (R 3.6.0)
 lattice       0.20-41  2020-04-02 [1] CRAN (R 3.6.2)
 nlme          3.1-147  2020-04-13 [1] CRAN (R 3.6.3)
 pkgbuild      1.0.6    2019-10-09 [1] CRAN (R 3.6.0)
 pkgconfig     2.0.3    2019-09-22 [1] CRAN (R 3.6.0)
 prettyunits   1.1.1    2020-01-24 [1] CRAN (R 3.6.0)
 processx      3.4.2    2020-02-09 [1] CRAN (R 3.6.0)
 progress      1.2.2    2019-05-16 [1] CRAN (R 3.6.0)
 ps            1.3.2    2020-02-13 [1] CRAN (R 3.6.0)
 R6            2.4.1    2019-11-12 [1] CRAN (R 3.6.0)
 Rcpp          1.0.4.6  2020-04-09 [1] CRAN (R 3.6.3)
 remotes       2.1.1    2020-02-15 [1] CRAN (R 3.6.0)
 rentrez       1.2.2    2019-05-02 [1] CRAN (R 3.6.0)
 rlang         0.4.5    2020-03-01 [1] CRAN (R 3.6.0)
 rncl          0.8.4    2020-02-10 [1] CRAN (R 3.6.0)
 rotl        * 3.0.10   2020-04-17 [1] Github (ropensci/rotl@0291cf1)
 rprojroot     1.3-2    2018-01-03 [1] CRAN (R 3.6.0)
 sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 3.6.0)
 vctrs         0.2.4    2020-03-10 [1] CRAN (R 3.6.0)
 withr         2.1.2    2018-03-15 [1] CRAN (R 3.6.0)
 XML           3.99-0.3 2020-01-20 [1] CRAN (R 3.6.0)
```
</details>

**Comment by fmichonneau** [comment]
I think I fixed this as part of 98cecc4a1580e9557acb67339eb560c63a6c2129

Please re-open if I missed something. Thank you for reporting!

**Comment by sckott** [comment]
thanks

**Comment by MichalisMihalitsis** [comment]
Hi, 
I am getting the same issue when trying to run the code:

Error in names(summary_match) <- c(names(tnrs_columns), "number_matches") : 
  'names' attribute [7] must be the same length as the vector [0]

Can you please advise on how to fix this? Haven't been able to find any info on it.
Best regards,
Mike

**Comment by fmichonneau** [comment]
Hi Mike,
Are you using the version from GitHub (installed with `remotes::install_github("ropensci/rotl")`) or the CRAN version?

The bug shouldn't be there in the GitHub version. Please let me know in either case.

**Comment by MichalisMihalitsis** [comment]
Hello Francois,
thanks for getting back to me so fast.
I was using the rotl package from the source you provided. I tried doing what you suggested and it works perfectly now. Thank you for the help provided.
Would you mind me asking, if there were any changes to the package? I have been using rotl for a few years now, and have found it very helpfull (see attached papers). So I'm just wondering if anything important changed.

Thanks again for your help!
Best regards,
Mike


Michalis Mihalitsis

PhD Candidate, Reef Fish Ecology and Evolution Lab

ARC Center of Excellence for Coral Reef Studies

James Cook University

Google Scholar<https://scholar-google-com-au.elibrary.jcu.edu.au/citations?user=2HfVmzYAAAAJ&hl=en&oi=ao>                              Research Gate<https://www.researchgate.net/profile/Michalis_Mihalitsis>


________________________________

**Comment by fmichonneau** [comment]
Hi Mike,

I'm glad you're finding rotl useful for your research!

Yes, there has been some changes but most have been relatively minor and tend to focus on keeping in sync with the updates that the OpenTree of Life team bring to the API to access the data that rotl relies on.

**Comment by sckott** [comment]
@fmichonneau I had assumes this would get to CRAN at some point. Do you still plan to send new versions to CRAN?

**Comment by fmichonneau** [comment]
@sckott newest release just accepted on CRAN. Apologies for the delay with this!
