### ISSUE TITLE
Linux install

### ISSUE THREAD

**Issue by jmjech** [ropensci/rotl#133]
I'm unable to install rotl on my Linux computer. I'm running Linux Mint, v19.3. For R I'm running v3.6.3.
The error messages I get when I attempt to load via the command line (sudo apt-get install r-cran-rotl) are:
The following packages have unmet dependencies:
 r-cran-rotl : Depends: r-api-3.4
               Depends: r-cran-httr but it is not going to be installed
               Depends: r-cran-jsonlite but it is not going to be installed
               Depends: r-cran-assertthat (>= 0.1) but it is not going to be installed
               Depends: r-cran-rncl (>= 0.6.0) but it is not going to be installed
               Depends: r-cran-ape but it is not going to be installed
               Depends: r-cran-rentrez but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
When I try to install any of dependencies, they seem to depend on r-api-3.4.

I get a similar set of errors when I attempt to install via Rstudio.

I am able to install in Windows 10 on my PC.

**Comment by fmichonneau** [comment]
For Linux, I encourage you to directly install it from R instead of your system terminal:

```r
install.packages("rotl")
```

**Comment by jmjech** [comment]
Initially I tried that, but "ape" wouldn't install, because it turns out that I hadn't installed gfortran.
So, I just installed gfortran (from the linux command line), then ape (in Rstudio), then rotl (in Rstudio, but I suspect it would have worked via the linux command line), and voila! I now have rotl on my linux box.
Many thanks!
