### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by ddenney1** [ropensci/rotl#135]
My advisor and I have been trying to troubleshoot some code using the latest version of rotl. 

For testing, I tried using the example tnrs_match_names("ananas") on my Windows laptop running R version 4.1.0 and the command works properly. However, when the same command is run on any of our Mac computers running R versions 3.6 or 4.03, the command returns this error: 

Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL certificate problem: certificate has expired

I am not sure if the calls to the API are handled differently using a Windows vs a Mac computer, but for some reason rotl is not allowing us to query the Open Tree of Life on any Mac computers.

**Comment by jakeberv** [comment]
I was having the same issue with R 4.0.3 on Mojave. I followed your instructions to install the latest version of curl and that seems to have worked.
