### ISSUE TITLE
studies_find_trees returning NULL match_tree_ids

### ISSUE THREAD

**Issue by LunaSare** [ropensci/rotl#136]
Hi @fmichonneau!

Running examples from `studies_find_trees` is returning `NULL` values instead of tree_ids in `$match_tree_ids` column:

```
> res <- studies_find_trees(property="ot:ottTaxonName", value="Drosophila",
+ detailed=FALSE)
> head(res)
     study_ids      n_matched_trees              match_tree_ids
1   pg_2407               2                                 NULL, NULL
2   ot_1046                1                                 NULL
3   ot_1047                1                                  NULL
4   ot_274                  1                                  NULL
5   pg_437                 1                                  NULL
6   pg_2443              10                               NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
 
```

This might be related to some change in the OpenTree API, but I can't identify where it is coming from. Any pointers are greatly appreciated!

Thanks for your time!

Cheers!

**Comment by fmichonneau** [comment]
closed with #137.
Thanks for the report and sorry for not being able to get to it before @snacktavish identified and addressed the issue.
