### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by noor-albader** [ropensci/rotl#141]
Hi 
I tried to use rotl:

```
library(rotl)
taxa <- rotl::tnrs_match_names(spp, context="Rice")
```

and get the following error:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL certificate problem: certificate has expired
```
anyone manning the website's url and its SSL certificate, could you please look into it?

Thanks!
Noor

**Comment by fmichonneau** [comment]
hi @noor-albader,

This is not a problem with rotl. Check out the discussion in #135 to see how to fix this. 

Thanks!
