### ISSUE TITLE
SSL Certificate Issue

### ISSUE THREAD

**Issue by tomjwebb** [ropensci/rotl#147]
Trying to use `rotl` for the first time and I'm hitting an SSL Certificate issue. Have tried various suggested solutions but in fact I think this might be an issue at OTL's end. I have tried just running some of the simple example code:
```
library(rotl)
apes <- c("Pongo", "Pan", "Gorilla", "Hoolock", "Homo")
(resolved_names <- tnrs_match_names(apes))
```
Which throws the following error:
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL peer certificate or SSH remote key was not OK: [api.opentreeoflife.org] SSL certificate problem: certificate has expired
```
I tried various solutions suggested here https://github.com/ropensci-archive/rbhl/issues/28 as I have recently updated both R and Mac OS, but these did not work. So I looked here https://forum.posit.co/t/ssl-certificate-problem-certificate-has-expired/68619 and tried running the code, substituting the otl API url:
```
x <- openssl::download_ssl_cert("api.opentreeoflife.org")
lapply(x, `[[`, "validity")
```
From this it looks like the first certificate expired yesterday. Is there a fix for this? Does this need raising with the OTL team?

For info, my system is:
```
R version 4.4.1 (2024-06-14)
Platform: x86_64-apple-darwin20
Running under: macOS Sonoma 14.6.1
```
But this problem is also occurring for my students running R4.4.0 and R4.4.1 under Windows 10 x64.

**Comment by jordandowell** [comment]
Just echoing, I am having the same issue, which seems to be that the SSL for OTL has expired.  running R4.4.0 aarch64

**Comment by tomjwebb** [comment]
Temporary fix until the certificate is updated, from Jonathan Chang on X: You can override SSL errors by using `with_config` from httr
```
cfg <- httr::config(ssl_verifypeer = FALSE)
httr::with_config(cfg, tnrs_match_names(c("Eviota")))
```

**Comment by adrientaudiere** [comment]
Thanks @fmichonneau for the information and @tomjwebb for the solution for my package.

**Comment by tomjwebb** [comment]
Thanks @fmichonneau!
