### ISSUE TITLE
releasing to CRAN

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/rotl#22]
I think we are pretty close to releasing rotl to CRAN.

If you have a minute, please look around and let me know if you find any bugs or things that we could improve. I'll try to finish/improve the vignette in the next few days.

I listed myself as maintainer. Are you (@dwinter and @josephwb) ok with it?

Also, I'm thinking of starting the onboarding process to have it on @ropensci ? Any objections?

**Comment by fmichonneau** [comment]
submitted to rOpenSci at ropensci/onboarding#17

**Comment by fmichonneau** [comment]
Just accepted on CRAN

**Comment by dwinter** [comment]
Nice!
