### ISSUE TITLE
drop all references to node_id(s)

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/rotl#41]
as they will be removed from the API  in the future (see OpenTreeOfLife/treemachine#183, OpenTreeOfLife/taxomachine#94), are confusing and unreliable.

**Comment by josephwb** [comment]
I wonder if we should reconsider this. Node IDs were present in v2 (but weird internal neo4j node ids). Now they look like "ott12345" (i.e. an ott_id) or "mrcaott123ott456". Node_ids are returned from a number of services (e.g. mrca, node_info), and can be used in others (e.g. subtree, induced_subtree).

**Comment by josephwb** [comment]
[Moving this from email thread to here]
@fmichonneau asked:
>Would this node id also have an OTT id? If not then I guess we need to reimplement them

Taxonomic nodes will have both an ott_id (e.g. numeric 12345) and a node id (e.g. character "ott12345"), while non-taxonomic nodes will only have a node_id (e.g. character "mrcaott123ott456").

**Comment by josephwb** [comment]
Ok, I am just putting these node_ids back in; we can always remove them later.

**Comment by josephwb** [comment]
Closing this, since (I believe) we decided against this.

**Comment by fmichonneau** [comment]
I'm looking over the documentation, and thinking about usability, and I'm now pretty sure it would be a good idea to be able to use node_id in some contexts. For instance, it doesn't seem too much of a stretch to imagine that you may want to get a subtree from a node that is not associated with a particular taxonomic level. So I think we may want to keep references to node_id for tol_subtree and tol_induced_subtree, and tol_node_info at least. Does that seem reasonable?

**Comment by josephwb** [comment]
Yeah, definitely useful for all tol methods. Don't know if taxonomy uses this, but in that case all nodes _are_ taxa.

**Comment by fmichonneau** [comment]
OK, that sounds good.

**Comment by josephwb** [comment]
Just to be clear, when I wrote:

>Closing this, since (I believe) we decided against this.

above I meant we decided against the **title** of this issue (i.e. we _do_ want to use 'em), _not_ that we decided against what I had done (i.e. implementing them). :bowtie:

**Comment by fmichonneau** [comment]
Got it. I think we are good for now.
