### ISSUE TITLE
Duplicate taxon names from OToL causes error

### ISSUE THREAD

**Issue by bomeara** [ropensci/rotl#46]
`get_study_tree(study_id="pg_710", tree_id="tree1277", tip_label='ott_taxon_name')`

Results in
`Error in rncl(file = file, ...) : 
  Taxon number 39 (coded by the token Pratia angulata) has already been encountered in this tree. Duplication of taxa in a tree is prohibited.`

Using `"original_label"` works, but presumably two tips were mapped to the same OpenTree taxon (which makes sense). I'd like to use the OpenTree names (they're already TNRS'ed) but there is this error (occurs in several of the 76 trees I'm trying to examine, so fairly frequent). I think the error is actually being thrown by rncl.

I'm not sure what the best behavior would be in this case. One approach would be to add a suffix to each of the duplicate taxon names; another would be to drop all but one of the duplicates randomly; a third would be avoiding this error but return a tree with duplicate names (i.e., ape is fine with duplicate names, so calling that instead of ncl in these cases might make sense, or rncl could be modified to avoid this problem itself).

**Comment by dwinter** [comment]
Thanks for the bug report @bomeara, I'll leave it to @fmichonneau to work out what rncl should do. Just thought I'd let you know of a possible work-around, in case this is a rate-limiting step for you at the moment. 

You can use the 'internal' api-mapping functions to get a character representation of the tree, and ape to read that tree (note, for the example at least I had to remove the spaces from taxon names):
```{r}
tr <- rotl:::.get_study_tree(study_id="pg_710", 
                             tree_id="tree1277", 
                             tip_label='ot:otttaxonname',  #triple 't', double ''n"
                             format="newick")
parsed_tr <- ape::read.tree(text=gsub(" ", "_", tr)
parsed_tr
```
```
Phylogenetic tree with 108 tips and 107 internal nodes.

Tip labels:
	'Helianthus_annuus', 'Canarina_canariensis', 'Jasione_montana', 'Legousia_hybrida', 'Campanula_asperuloides', 'Campanula_latifolia', ...

Rooted; includes branch lengths
```
Hope that's some help to you, and that we can find a less hack way for this to work in the long run :)

**Comment by bomeara** [comment]
Beautiful, @dwinter, thank you. This will work nicely for now (datelife update to pull from OpenTree). 

Minor note for those using the example: there's a missing right parens on this line
`parsed_tr <- ape::read.tree(text=gsub(" ", "_", tr))`

[Relevant XKCD](https://xkcd.com/859/)

**Comment by fmichonneau** [comment]
Thanks for bringing this up.

The issue is that NCL follows the strict definition of the NEXUS file format that doesn't allow duplicated taxon names. I don't think there is an easy way to fix this in the C++ code.

I think the best option would be to add a suffix, I'll try to implement this in a couple of weeks when I'm back home.

**Comment by fmichonneau** [comment]
Hi @bomeara,

I implemented a fix for this. With `get_study_tree` duplicated labels will be disambiguated by adding a suffix `_1`, `_2`, `_3`, etc. before being parsed by NCL.

If you have a chance to give it a try, please let me know how it works for you.

**Comment by bomeara** [comment]
Yes, this seems to work. Thanks!
