### ISSUE TITLE
handle better query limits (and figure out what they are)

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/rotl#56]
User reported that `tnrs_match_names` accepts up to 100 species and otherwise throws cryptic error message.

`rotl` should check input and do the appropriate API calls so that it works.

**Comment by josephwb** [comment]
Is there an example call that fails?

**Comment by josephwb** [comment]
Seems like [the limit is 1000](https://github.com/OpenTreeOfLife/taxomachine/blob/master/src/main/java/org/opentree/taxonomy/plugins/tnrs_v2.java#L45) (not 100).

**Comment by josephwb** [comment]
Here is the [relevant bit](https://github.com/OpenTreeOfLife/taxomachine/blob/master/src/main/java/org/opentree/taxonomy/plugins/tnrs_v2.java#L234-L238).

**Comment by fmichonneau** [comment]
I tried with the data provided by the user but it looks like it comes from issues with the names rather than the size. Closing for now.
