### ISSUE TITLE
add argument `include_lineage` to `taxonomy_lica()`

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/rotl#58]

**Comment by josephwb** [comment]
This is now called "mrca" in the API, and does not have a "include_lineage" argument. Trying to [figure this out](https://github.com/OpenTreeOfLife/germinator/issues/79).

**Comment by josephwb** [comment]
Hmm. Seems like this is still an arg for the method, but it is [missing from the documentation](https://github.com/OpenTreeOfLife/germinator/issues/79).

**Comment by fmichonneau** [comment]
closed by 1fbd68c2feccf1f066bc1e6002e28bb09bff1b6b
