### ISSUE TITLE
feedback on opentree v3 API

### ISSUE THREAD

**Issue by kcranston** [ropensci/rotl#64]
Just an FYI that we will be releasing a new version of the OpenTree APIs within the next few weeks. Here is the [draft documentation for v3](https://github.com/OpenTreeOfLife/germinator/wiki/Open-Tree-of-Life-Web-APIs) and the [draft release notes](https://github.com/OpenTreeOfLife/germinator/wiki/Release-notes-for-web-API-v3). We will post on announcements list, twitter, etc once these are live, but wanted to give you a heads up. Feedback welcome, including feedback about 'please finalize X sooner than later'.

**Comment by dwinter** [comment]
Thanks for the heads up @kcranston,

Will look at these in more detail later, but at a glance all the "locked in" changes make sense and shouldn't be too difficult to accommodate. 

For the under-consideration changes, returning 4xx codes for all errors makes sense. On the other hand, `rotl` does check for and handle the existing "error-ish" returns so it wouldn't change anything for us.

**Comment by kcranston** [comment]
Glad to hear there is nothing panic-inducing in the proposal! I'll let you know when we have a beta version deployed on our development servers that you can use for your own testing.

**Comment by fmichonneau** [comment]
Thanks @kcranston! Yes, the changes look good, and should be easy to implement for us. Do let us know when there is a beta version available!
