### ISSUE TITLE
Differentiate `nearest_taxon` from `taxon` for the taxonomic methods associated with `tol_mrca`

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/rotl#77]
I implemented the "taxonomy" methods to the objects returned by `tol_mrca()` so that we can use the function `unique_name`, `rank`, `ott_id`, etc... on the output. Currently, the method outputs the taxonomic information in the same way regardless of whether the taxon is actually associated with the node matched by the MRCA requested, or whether it's the nearest_taxon to the node associated with the MRCA. Should we differentiate the two? if so, how? Should we output a warning or a message if it's the nearest taxon? Or should we name the list "nearest_taxon" or "mrca" like OTL does? Or maybe with the node_id (it would be `mrcaottXXXottYYY` if it's not a taxon and `ottZZZZ` if it is)? Something else?

**Comment by fmichonneau** [comment]
As it stands, I opted for the last option. Feedback welcome:

```r
> tax_name(hol)
$ott5004030
[1] "Holothuria"

> tax_name(birds_mrca)
$mrcaott246ott5481
[1] "Neognathae"
```

**Comment by josephwb** [comment]
I'm not sure I understand the issue, but the example above looks confusing. Node `mrcaott246ott5481` does not have the name "Neognathae" (I know you know this, I am just saying that a user might think that?) .The `nearest_taxon` need not be all that close to the mrca node; in a heavily sampled (i.e. resolved) clade the nearest taxon may be _many_ nodes rootward of the mrca node.

I think a distinction needs to be made.

**Comment by fmichonneau** [comment]
I agree it's going to be confusing. I worked on making the output of the taxonomic methods more homogeneous, and in the process settled to add an attribute for this case that describes whether it's the taxon is the mrca or the nearest_taxon:

```{r}
>  birds_mrca <- tol_mrca(ott_ids=c(412129, 536234))
> tax_name(birds_mrca)
$Neognathae
[1] "Neognathae"

attr(,"taxon_type")
[1] "nearest_taxon"
```

thoughts?

**Comment by fmichonneau** [comment]
@josephwb do you think this approach is OK?

**Comment by josephwb** [comment]
Sure. It is a bit clunky no matter what, so this seems fine.

**Comment by fmichonneau** [comment]
Agreed...
