### ISSUE TITLE
Regenerate README before CRAN release

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/rotl#78]
just so we don't forget

**Comment by dwinter** [comment]
Just a note to say the current readme has a warning message that we don't discuss at all ( I don't think it came up when it was first written). If it persists we should remove that taxon or discuss the warning (there might be a clue in the new `resolved_names`  table)

**Comment by fmichonneau** [comment]
good catch... it looks like there is an insect with that genus name. But it looks like a mistake from OTL as the original source ( IRMNG - Interim Register of Marine and Nonmarine Genera ) lists it as unavailable (nomen nudum). In any case, probably easier to just remove that name from the README
