### ISSUE TITLE
Returns ellipsis rather than all tree_id

### ISSUE THREAD

**Issue by bomeara** [ropensci/rotl#85]
If I do `rotl::studies_find_trees(property="ot:branchLengthMode", value="ot:time", verbose=TRUE, detailed=TRUE)` or `rotl::studies_find_trees(property="ot:branchLengthMode", value="ot:time")` I get a data.frame with relevant information. However, if there are 5 or more trees, the `tree_ids` column (and `match_tree_ids` if present) give only five labels, then ",...". Oddly, it does this even when there are only five, but in all cases it's an issue: I'm trying to get all the trees and it's giving me only a subset. Is this an API issue or an rotl issue? Example:

```
chronogram.matches <- rotl::studies_find_trees(property="ot:branchLengthMode", value="ot:time", verbose=TRUE, detailed=TRUE)
chronogram.matches$tree_ids[which(chronogram.matches$n_trees>4)]
```

**Comment by josephwb** [comment]
Hey @bomeara. I this is is on rotl. Looking into it now, but @fmichonneau (I believe) wrote this part :bowtie:

**Comment by josephwb** [comment]
Ah, here we are:
```R
## Unexported function that limit the display of tree_ids to the first
## 5 values.
limit_trees <- function(x) {
    if (length(x) > 4)
        x <- c(x[1:5], "...")
    paste(x, collapse = ", ")
}
```

**Comment by josephwb** [comment]
Looks like `limit_trees` is used only in `studies_find_trees` and (unexported) [`summarize_meta`](https://github.com/ropensci/rotl/blob/master/R/studies-utils.R#L5-L46).

**Comment by josephwb** [comment]
@bomeara I can fix this easily, but the result will still be a single string with comma delimited ids. In other words, you will have to split the string yourself. Is that fine?

**Comment by bomeara** [comment]
Yep, that's great. Thanks!

**Comment by josephwb** [comment]
Ok, will do. Will push shortly.

**Comment by josephwb** [comment]
Ok, pushed. `tree_ids` is still truncated to 5 (with ellipsis if _more than_ 5), but `match_tree_ids` is returned in its full splendor. So, for your example, instead of:
```
chronogram.matches$tree_ids[which(chronogram.matches$n_trees>4)];
```
you want:
```
chronogram.matches$match_tree_ids[which(chronogram.matches$match_tree_ids>4)]
```
(I can return all tree ids in both columns, if that is desired, but it seems you want only the matched ones).

Do (as you know):
```
require(devtools);
install_github("ropensci/rotl");
```
Gratuitous emoij :skull:

**Comment by bomeara** [comment]
👍 Thanks!
