### ISSUE TITLE
Subtree not pruning correctly

### ISSUE THREAD

**Issue by bomeara** [ropensci/rotl#89]
I want to get just the ingroup tree from OT trees. 

`rotl::get_study_subtree(study_id="pg_420", tree="tree522", subtree_id="ingroup")`

and 

`rotl::get_study_tree(study_id="pg_420", tree="tree522")` 

Give trees that have 171 taxa, but the former should have only 169 (according to @josephwb). The examples in the help for get_study_subtree also don't seem to be affecting the ntips returned. I'm using the CRAN version of rotl.

**Comment by fmichonneau** [comment]
it should be fixed now (in 3.0.1.901 from GitHub). Let us know if you notice something wrong. Thanks for the reports!
